name = "BasicBlackHoleSim"
uuid = "85eb58d7-e894-4321-a0d0-3cd5d3813362"
version = "0.1.0"
authors = ["jonesdwill <jonesdwill@outlook.com>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
DataFrames = "1.8.1"
DifferentialEquations = "7.17.0"
Plots = "1.41.2"
Revise = "3.12.3"
